sudo: required
language: java
jdk: oraclejdk11

services:
  - mysql
  - docker

env:
  global:
    - secure: "KxNw1mxKbQXPn6X2CMehMOKJmfbr67jw8KVqM6Dwrjwqu9okasJSdCsdlhjl1tgh5dLIHp5Qq847KR8UKDFW5WroUp3rC9rEb11ADCIkkS44EbibeWvPrbfZrMuAEdUX+2n68aWil9idHi+h0pANAN90WAqIsyqrbqnzac7vcJNbLp9U2CsrJ52oQLeo7sCCKzmcbzdIfeJ91JaGuKoqhylkf+Rel9PtBwKf8uXy1k8l7pMmcdS8wvDy8zqUs5eaJiTrjpzunAt7kKkQJjimhzxcM8v4AZlABfuYbNKNFB5+t0W+wDyhqfqtM8uUGhZkccYNHJftkbuKw9aeUqsjYHO+l1ZY7XYXtvsHBWIxRIg1c3DciVi5kO6Uc2vqh1lklqNMN86YzQoLaB/A8zjM3FcxW0QXmnZtXLTOX2BAT5HzUenjXE0+pAUeFU56p9AMaR4rq859alkQ3OhbsBL6+uABbqopqVd/uxhAKYCfGOWJY3toqK7k1IbsKsZTxsRv4oGA1qLaDOhiP+LzjJ9WH2kJPhwBrgGlOTiUyIERdq3YycDMo9Neiflo6HfgNziFDLV367Q/YA73KSHvo32iRfdfY1Poqqgr4StsJshpbYAgJBrdaH8DTL09tWc6/Xo/bhQ7ZnxQIdY2NdPrODkZxBeEjOcffc7HlVax14cJSTI="
    - COMMIT=${TRAVIS_COMMIT::7}


addons:
  sonarcloud:
    organization: "rikp777"
    token:
      secure: $SONAR_TOKEN

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"

before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
