sudo: required
language: java
jdk: oraclejdk11
services:
- mysql
- docker
env:
  global:
  - secure: "BIZ0eQMY7A+7gLta/K8lBiWMiWYQnT1rG11PfQjGbPJjiAtZkj1RfaLow2HB+IuPUWLufZ44KmTKczdIpTuU4c1oCDBXpJE5LYRTjK4NuxIKyDBoOVciAJ7oE48ey+ys94RX8rP0KWpviQnwNNFN8MfBO/IhifX/fdJzJhKLtK1i/Ea97SXBjXk8AEPtESD/4mSMJYpPHNFe/F4RR6yaT3ygye0So/4DsH5BxZb03t+B6yfd2+eD8hwiTeLW2ms6kTKkgfbJR5I3UKd/1zJlvz7i6ZO2dHeyBukP5TXdchBkJRC9IBLa2aTcHvrt1h5Qvy+p2ono1YKI/Vgb9vP2Qy2l6h6YrZPmbI3DA9LwiZySh2KV8zF+du0PTpQadnbUfSLST+MnjvOvIVkcjnb4h6u/EeFbOWVKKSNpF5MFaHfJ6TmuyKYGKtQlJbrg72erdZnzBzOldIXr+ZpdsCstOfr/+y2uFc2YcMg7ZfPnAaci51plgxKl9T0wiouhjCOVICGuLRc+HwGnOLBBjgSD5X7ZJm0dXLBTNrotm/wTmGR7p+a18YeutyNLUr4FdyLkox3aIhcE8dIBBDV54ROFCYclhqs0YY4hbcWZ8jaYFdpg2hO1ZK/oSZFEbVYwLqMmh/5JEDq6kjCnIL+naTKU+DIu25+x5Az3rwpTP93pMCI="
  - COMMIT=${TRAVIS_COMMIT::7}
addons:
  sonarcloud:
    organization: "rikp777"
    token:
      secure: $SONAR_TOKEN
script:
- "./mvnw clean install -B"
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=rikp777_MyKoiPond -e -X
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- chmod +x mvnw
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
