language: java
jdk: oraclejdk11
env:
  global:
  - secure: LOepbURohSlkQIt9M6fQxkgi2G6pUk7SK+zZhdjebHpPEQzjiwIik2ZF59SwANx5k5LPXLlkinYrcKTRN8zWCXTaMR1ZKtWQFuPMBq+i7DqfzYU16hOL0wiR77AH2Dlt7xo7mWADMpqHEnp+681zYlqmfXNY2W5S3A2bz13ljLse1HjtFKXaCpR0SzY7dUXhRGLFpl683TQ0B4kcLtsUKWPb/cL07JG0Z/LaCzJzX3rMVripMlTtrMIG0p0sOUJGoJW9pM1rJQ6o9UOnlDcMS/UtBevS3Jj+RdRJXqoDSCAo5mlWmrjNQROEhY6Ny7oVQs4fwWIuGaIoG3K9USW4VILK14xJ/llDlvFsjRzSA/AnBvI1oKbrMOSRS86lQgoDZE8DgfAEDC6K7t7CQi2KYQuv/i8F1C2rKOpLGXYfXOy2jVm3QcOcSfVlcAnmOil+m6Ty953WxEONDIPCKlKrcSR5R9lZCkn/gtFfbDiM1NhrC6EiGqZ8ifHwwewBbp7JsAJbGuhsW5qWfBEKBePFdrpGqr6p7sstDHp+8WKFA2jFjmGYl0JDScwuHKjUTV2Rss3IwwQhIYRZOq8ZsYHqq0SOc78fyaYNLa9G6K7AfA55sIFCG/gp3h2+vLz2tfc9Rg7WmrFS7UlvWTWnxzPj7QeyTOjZH1lBhhE91dQc2Io=

addons:
  sonarcloud:
    organization: "rikp777-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacocoprepare-agent package sonar:sonar
services:
- mysql
- docker
before_install:
- chmod +x mvnw
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
