sudo: required
language: java
jdk: oraclejdk11

env:
  - MAVEN_VERSION=3.3.9

services:
  - docker

addons:
  sonarcloud:
    organization: "rikp777"

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"

before_install:
  - chmod +x mvnw

script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=com.api:mykoipond
  - docker build -t docker.io/$DOCKER_USERNAME/my-koi-pond:latest .

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push docker.io/$DOCKER_USERNAME/my-koi-pond:latest
  - bash <(curl -s https://codecov.io/bash)
