sudo: required
language: java
jdk: oraclejdk11
services:
- mysql
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: AnZRmv7+W5LL8uZ+D1p8P+TClDfXGLxOElWBYbUXgaTCLT4ylw1AV/uEP+VKoqNYUAxaQ+BIiLBuohkizDRC4uplFaqhTwGxTQKN///H2uOZwnVLZMDTZTmhdQkiQwy61N5qY7b93RRhFeuR8dS7w8F38CoA5eE8youf+jUR9V5pn0pIDSNHTQdmPBac+WYOU8GOWUqSi2uZ4fEUfwNM913ia1ed+art5hHEA/265YZPpM6jZ5UZdYBGqTzBMCB8tQ7l3V2TcwbvI8UUdF6n9JkG/RGkCauYtdQAhtvGXz2wHGtWSFH0iNHjTLDhlQMVyxsM+5bZuci9r1Yf8Cj9nLcO1O9SuqnbvMGNRN4q8Lf2VCnmsMiIciBGTByjiX1Gm/RRUMAJWymaGyxjgO4qvuQM2Bg5Ndhd5QX0CvjpJe4/fPoZ4iKYDsqDwGebE0jPPbiS9fvI+gT2yH94GVEwaj9mSpPsmwfQ2aKXzM/kiz4pXEIr5N2eDHANuWjbtlpE+gX3I/CQfxnRe4s1l4r3Ok9VuGK09gqIrT0CauA/c9OuUBlVfW/PIs1noZtMrz4rsUVMEmZqJnsLBDP/8dhIddUx6Jp0qXkqJA9cGScylOEp0CmT7dnTiSuRzviII6Aedm5pMcd9AWVP1/jzf5W6bFQ1Mzsk8iyXFeZTJ8MoxIk=
addons:
  sonarcloud:
    organization: rikp777
    token:
      secure: AnZRmv7+W5LL8uZ+D1p8P+TClDfXGLxOElWBYbUXgaTCLT4ylw1AV/uEP+VKoqNYUAxaQ+BIiLBuohkizDRC4uplFaqhTwGxTQKN///H2uOZwnVLZMDTZTmhdQkiQwy61N5qY7b93RRhFeuR8dS7w8F38CoA5eE8youf+jUR9V5pn0pIDSNHTQdmPBac+WYOU8GOWUqSi2uZ4fEUfwNM913ia1ed+art5hHEA/265YZPpM6jZ5UZdYBGqTzBMCB8tQ7l3V2TcwbvI8UUdF6n9JkG/RGkCauYtdQAhtvGXz2wHGtWSFH0iNHjTLDhlQMVyxsM+5bZuci9r1Yf8Cj9nLcO1O9SuqnbvMGNRN4q8Lf2VCnmsMiIciBGTByjiX1Gm/RRUMAJWymaGyxjgO4qvuQM2Bg5Ndhd5QX0CvjpJe4/fPoZ4iKYDsqDwGebE0jPPbiS9fvI+gT2yH94GVEwaj9mSpPsmwfQ2aKXzM/kiz4pXEIr5N2eDHANuWjbtlpE+gX3I/CQfxnRe4s1l4r3Ok9VuGK09gqIrT0CauA/c9OuUBlVfW/PIs1noZtMrz4rsUVMEmZqJnsLBDP/8dhIddUx6Jp0qXkqJA9cGScylOEp0CmT7dnTiSuRzviII6Aedm5pMcd9AWVP1/jzf5W6bFQ1Mzsk8iyXFeZTJ8MoxIk=
script:
- "./mvnw clean install -B"
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=rikp777_MyKoiPond
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- chmod +x mvnw
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
