language: java
jdk: oraclejdk11

script:
  - ./mvnw clean install -B

services:
  - mysql

before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

#script:
#  - ./mvnw clean install -B
