sudo: required
language: java
jdk: oraclejdk11
services:
- mysql
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: drH0OISYp9qkGZ9deVSEomcSPKXXSX7KF/jVBhhPv4JEjz/EcJIpc4pxZZDA+41YD1coPph8R83eh+mXe9AYgeoMiglwgT3y2VwfaQXWS1vlp/l3pGgF/4gdKbPIwWbN2kV2fxBCZk/SqAdjCTv5DIRFP7apID8EOh3DL08R1OTS5+YKvQWkekHJ7NkSrOPCAQHhu0H/fK4eCjdsLLYC8uqfbW76lXINPuoUmeyv+SiIfBnTGoRSLELIYGpCVRsxvrOhMev0u1h8wBf/hGmywg2JIPUPlqiJtMDlEPQTtxSg7WSbiJLcwkDGX2IjBQNSRXcMuk69ooVIlRTu6tAM8ENVaerkwGLPN3yL2rnQNvOfOI54+7Ka2ZoCo6Ye4c9467tNuufPmMqf3WqgFgl4/wSIwv76RUB+ZLN95dr+XpPMsWpwyNN4BbFIaFvE5pPLXwEq5jIiMHvQuUZHKfAR7WdM2Bl++PvMkWQlEYUt4qlsfm+nagqe5+gWfMBpjgKTs42cxDfDP/Zjn8e5QU1/IikSywWEpSv6iRemAuMLS5CQps5q2mrWpFXTjagzFfjc6+Ht/jIjH9I+GyTf8d11+iQmO5/8UMX/CPBpu25I1wt82jd10jX09C+mgYHqSCj5E4yIL7qnI8bvgorgpu6xRGTCOhUka7SAOicVG6oG9rY=
addons:
  sonarcloud:
    organization: rikp777
    token:
      secure: drH0OISYp9qkGZ9deVSEomcSPKXXSX7KF/jVBhhPv4JEjz/EcJIpc4pxZZDA+41YD1coPph8R83eh+mXe9AYgeoMiglwgT3y2VwfaQXWS1vlp/l3pGgF/4gdKbPIwWbN2kV2fxBCZk/SqAdjCTv5DIRFP7apID8EOh3DL08R1OTS5+YKvQWkekHJ7NkSrOPCAQHhu0H/fK4eCjdsLLYC8uqfbW76lXINPuoUmeyv+SiIfBnTGoRSLELIYGpCVRsxvrOhMev0u1h8wBf/hGmywg2JIPUPlqiJtMDlEPQTtxSg7WSbiJLcwkDGX2IjBQNSRXcMuk69ooVIlRTu6tAM8ENVaerkwGLPN3yL2rnQNvOfOI54+7Ka2ZoCo6Ye4c9467tNuufPmMqf3WqgFgl4/wSIwv76RUB+ZLN95dr+XpPMsWpwyNN4BbFIaFvE5pPLXwEq5jIiMHvQuUZHKfAR7WdM2Bl++PvMkWQlEYUt4qlsfm+nagqe5+gWfMBpjgKTs42cxDfDP/Zjn8e5QU1/IikSywWEpSv6iRemAuMLS5CQps5q2mrWpFXTjagzFfjc6+Ht/jIjH9I+GyTf8d11+iQmO5/8UMX/CPBpu25I1wt82jd10jX09C+mgYHqSCj5E4yIL7qnI8bvgorgpu6xRGTCOhUka7SAOicVG6oG9rY=
script:
- "./mvnw clean install -B"
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=rikp777_MyKoiPond
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- chmod +x mvnw
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
