sudo: required
language: java
jdk: oraclejdk11
services:
  - mysql
  - docker

addons:
  sonarcloud:
    organization: "rikp777"
    token:
      secure: "E+Ahzeu0pcKPSuRKLoQM8+c8LqA13vy8rLADuVXFCvCGcwrHEx4lOydSvwkLvn3Szj5GUrV/wU/kXYbEsTNwqDgSaD8MU36wdkR/sIdHx75dRZfytTx6JkdUXir6gX1tZvgYAUhuiqh5yHDw2X7AuiO/F4NEDcRL5xiGWFKiZU2K61aIc+37wPWQGOUxMZBy8iantjyV1qeveuh13/HY26aWMoekQLOCF5hIN1fgd/EG2jUsT+t9CPCkCouuVceXpWjVxUi8LloN4H37Wj1olZiQIEM86/6AmKQkYeDvlxlm5NnCEPM4jaN1v8QdJnHMfgtY1Yu2He3aaGj650HysJ+AqZhkttglyEj6ZKXFsJ/6xHOlQcdC7EwWwya68wVF5LlWvalyEVppgQchrVaAhpnLO+dlBJJWf2TqWJXCbwQI/Dvu3dK/92soVjSd3eecfZOI9Bxta73+AErwV1+MwwvqBtYloaFNMZpouF8rmwbgRlHnmntUJxhdA14acwzAqJxNmDLwTKFyLt6ZG5w0EllOkwIZ0NAh99beYYQiEUH1uPsLNtWiCRMhoQ4Cwh2bHAGBqTfMUgtmJqIOPRUSnFaNs4IiobPseGd6cqXknVYTOm4+EtehJgVbMIihUWeiRmqngTd0S+DcUenBOROXp6Um2fG3CMuxksy+3hBptoo=" #encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
