sudo: required
language: java
jdk: oraclejdk11
services:
  - mysql
  - docker
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - secure: "LYJgRSp0Au9DWqEDVz+bfpLekDGJuLWm8exOExwYgoYM9t9ccwgFECPEHbEvy94fRA96E7k97e2/+YCD/TpQG3d5QZOFjyUJIRb8kX/TesE3rRWcaVS/tNLKvRBpnvGJCG5LmuHOjaxmrGP4jh8bpyDag/NokmXooxSR23jZ6HDdL2t71onMA70uyi77xouTepZG/cqzGeF3CFOw1oAYSv1qaFyufZ80+Y1V8iYXpxN7Cbw8XDuuazCGD6ACYDcrxt7Vpqw9vXPs77pq8FCQ71YW5M4sjWL60uxhbBK1vbdecQkfHq7AnyP1yJ7o19rbeZSkkiqJjKEEz7A/CMFZuSmGg6xLeGU/ugdxvGhvX9SD5LWLU2eUOoeAOOVW3PMaaG/PnwJAtRh5qd9LXGQ0bXD+QuhHtNdWhiCp6hSMgDQSrTNdADucBFJdu16jQk6iSQQEiQ5fuGVkikkNeHWNoCNMXRfN9l2/HwWANAltdAotZlf0pymoZB0NQA/QToNsl0mQkJqgHATI7/6icWvcfe4Sdpp7NVJkF/c9JhLrp5qokSrMOhpMDacmuZpXLg+x+bC0yhQJsbKNZUFoxl+ThB5ycQy/WzDHzRgeUGrQqoWUkBO7+5QOa1Xma5a0QlY6j1DpDQwupuJ9t1EYnyNpwBOqHJ64DWI6YTEriWCXmtw="
addons:
  sonarcloud:
    organization: rikp777
    token:
      secure: "LYJgRSp0Au9DWqEDVz+bfpLekDGJuLWm8exOExwYgoYM9t9ccwgFECPEHbEvy94fRA96E7k97e2/+YCD/TpQG3d5QZOFjyUJIRb8kX/TesE3rRWcaVS/tNLKvRBpnvGJCG5LmuHOjaxmrGP4jh8bpyDag/NokmXooxSR23jZ6HDdL2t71onMA70uyi77xouTepZG/cqzGeF3CFOw1oAYSv1qaFyufZ80+Y1V8iYXpxN7Cbw8XDuuazCGD6ACYDcrxt7Vpqw9vXPs77pq8FCQ71YW5M4sjWL60uxhbBK1vbdecQkfHq7AnyP1yJ7o19rbeZSkkiqJjKEEz7A/CMFZuSmGg6xLeGU/ugdxvGhvX9SD5LWLU2eUOoeAOOVW3PMaaG/PnwJAtRh5qd9LXGQ0bXD+QuhHtNdWhiCp6hSMgDQSrTNdADucBFJdu16jQk6iSQQEiQ5fuGVkikkNeHWNoCNMXRfN9l2/HwWANAltdAotZlf0pymoZB0NQA/QToNsl0mQkJqgHATI7/6icWvcfe4Sdpp7NVJkF/c9JhLrp5qokSrMOhpMDacmuZpXLg+x+bC0yhQJsbKNZUFoxl+ThB5ycQy/WzDHzRgeUGrQqoWUkBO7+5QOa1Xma5a0QlY6j1DpDQwupuJ9t1EYnyNpwBOqHJ64DWI6YTEriWCXmtw="
script:
  - "./mvnw clean install -B"
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=rikp777_MyKoiPond
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
