describe('Breed functionality', () => {
    it('Button click update Breed', () => {
        cy.visit('http://127.0.0.1:8080/breed')
        cy.get('#update-Shusui').click()
        cy.get('#name')
        cy.contains('Shusui')
    })
    it('Back from Update to Create', () => {
        cy.visit('http://127.0.0.1:8080/breed')
        cy.get('#reset').click()
        cy.get('.card-title')
        cy.contains('create')
    })
    it('Button click Delete to delete component', () => {
        cy.visit('http://127.0.0.1:8080/breed')
        cy.get('#delete-Shusui').click()
        cy.get('.card-title')
        cy.contains('delete')
    })
    it('Submit create new breed', () => {
        cy.visit('http://127.0.0.1:8080/breed')
        cy.get('#name').type('test')
        cy.get('#description').type('test')
        cy.get('#create').click()
        cy.get('#error')
        cy.contains('success')
    })
    it('Submit create new breed but does not suffice', () => {
        cy.visit('http://127.0.0.1:8080/breed')
        cy.get('#name').type('t')
        cy.get('#description').type('t')
        cy.get('#create').click()
        cy.get('#error')
        cy.contains('error')
    })
    it('Submit update breed', () => {
        cy.visit('http://127.0.0.1:8080/breed')
        cy.get('#update-Shusui').click()
        cy.get('#update').click()
        cy.get('#error')
        cy.contains('success')
    })
    it('Submit update breed but does not suffice', () => {
        cy.visit('http://127.0.0.1:8080/breed')
        cy.get('#update-Shusui').click()
        cy.get('#name').clear()
        cy.get('#name').type('t')
        cy.get('#description').clear()
        cy.get('#description').type('t')
        cy.get('#update').click()
        cy.get('#error')
        cy.contains('success')
    })
    it('Submit delete breed', () => {
        cy.visit('http://127.0.0.1:8080/breed')
        cy.get('#delete-Shusui').click()
        cy.get('#delete').click()
        cy.get('#error')
        cy.contains('success')
    })
})
