describe('SubBreed functionality', () => {
    it('Button click update SubBreed', () => {
        cy.visit('http://127.0.0.1:8080/subbreed')
        cy.get('#update-Nidan Kohaku').click()
        cy.get('#name-input')
        cy.contains('Nidan Kohaku')
    })
    it('Back from Update to Create', () => {
        cy.visit('http://127.0.0.1:8080/subbreed')
        cy.get('#reset').click()
        cy.get('.card-title')
        cy.contains('create')
    })
    it('Button click Delete to delete component', () => {
        cy.visit('http://127.0.0.1:8080/subbreed')
        cy.get('#delete-Nidan Kohaku').click()
        cy.get('.card-title')
        cy.contains('delete')
    })
    it('Submit create new SubBreed', () => {
        cy.visit('http://127.0.0.1:8080/subbreed')
        cy.get('#name').type('test')
        cy.get('#description').type('test')
        cy.get('#create').click()
        cy.get('#error')
        cy.contains('success')
    })
    it('Submit create new Sub Breed but does not suffice', () => {
        cy.visit('http://127.0.0.1:8080/subbreed')
        cy.get('#name').type('t')
        cy.get('#description').type('t')
        cy.get('#create').click()
        cy.get('#error')
        cy.contains('error')
    })
    it('Submit update subbreed', () => {
        cy.visit('http://127.0.0.1:8080/subbreed')
        cy.get('#update-Nidan Kohaku').click()
        cy.get('#create').click()
        cy.get('#error')
        cy.contains('success')
    })
    it('Submit update SubBreed but does not suffice', () => {
        cy.visit('http://127.0.0.1:8080/subbreed')
        cy.get('#update-Nidan Kohaku').click()
        cy.get('#name').type('t')
        cy.get('#description').type('t')
        cy.get('#create').click()
        cy.get('#error')
        cy.contains('success')
    })
    it('Submit delete SubBreed', () => {
        cy.visit('http://127.0.0.1:8080/subbreed')
        cy.get('#delete-Nidan Kohaku').click()
        cy.get('#delete').click()
        cy.get('#error')
        cy.contains('success')
    })
})
